### ISSUE TITLE
good share

### ISSUE THREAD

**Issue by 1sn0m4d** [LiGhT1EsS/pam_my_unix#1]
pam 这个算是比较常见的后门了。
感觉差了一点东西
假设你做一个密码记录 要是你没有访问权限呢
是不是像其他的一样
加一个万能密码 正向才能连接呢

**Comment by lightless233** [comment]
你的意思我明白，PAM确实是可以用作后门，也考虑过这方面的问题：）

但是我这个项目的本意并不是作为后门使用的，而是装在自己的机器上，记录其他人爆破过来的字典，然后再将流量弹回去，所以这个模块暂时只有记录密码功能XD
